on:
  workflow_dispatch:
  push:
    tags:
      - '*'

name: release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Core
        run: |
          git clone https://github.com/${{ secrets.REPO }} .
          ref="$(git describe --tags --abbrev=0)"
          git checkout "${ref}"
      - name: Go Version
        id: get_version
        run: |
          GOVER="$(curl -sLf 'https://golang.org/VERSION?m=text' | grep "go")"
          echo "GO_VERSION=${GOVER#go}" >> $GITHUB_OUTPUT
      - name: Setup-go
        uses: actions/setup-go@v4
        with:
          go-version: '${{ steps.get_version.outputs.GO_VERSION }}'
          check-latest: true
      - name: Get project dependencies
        run: go mod download
      - name: Release
        run: | 
          CGO_ENABLED=0 go build -o release -trimpath -ldflags "-s -w -buildid=" ./main
          zip -9vr release.zip release
      - name: Install minisign and sign
        run: |
          sudo apt-get -y install libsodium-dev
          git clone --depth 1 https://github.com/jedisct1/minisign.git
          cd minisign/src
          mkdir -p /tmp/bin
          cc -O2 -o /tmp/bin/minisign -D_GNU_SOURCE *.c -lsodium
          cd -
          /tmp/bin/minisign -v
          echo "${{ secrets.MINISIGN_SK }}" >> /tmp/minisign.key
          echo | /tmp/bin/minisign -s /tmp/minisign.key -Sm *.zip
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.TOKEN }}
          file: ./release.zip*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          
